# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
# ----- Build Stage -----
FROM node:18-slim

# Create app directory
WORKDIR /usr/src/app

# Copy all source files
COPY . .

# Install dependencies
RUN npm install

# Build the project
RUN npm run build

# Remove development dependencies
RUN npm prune --production

# Set executable permissions
RUN chmod +x dist/src/server.js bin/mcp-think-tank.js bin/mcp-think-tank-cjs.cjs

# Run as non-root user
USER node

# Start the server
CMD ["node", "dist/src/server.js"]

# Label the image
LABEL org.opencontainers.image.source="https://github.com/flight505/mcp-think-tank"
LABEL org.opencontainers.image.description="An MCP server that provides reasoning and knowledge graph capabilities for AI assistants"
LABEL org.opencontainers.image.licenses="MIT"